#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
python3 -m pip install --requirement ./.devcontainer/requirements.txt

CUSTOM_INTEGRATION_ROOT=${PWD} cookiecutter gh:lalexdotcom/ha-custom-integration-template --checkout=`jq -j '.template' ./.devcontainer/config.json`